name: neonote

description: A Flutter note-taking app with AI capabilities

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.3
  file_picker: ^10.2.0
  shared_preferences: ^2.2.3
  markdown: ^7.2.1
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0
  ffi: ^2.1.2
  provider: ^6.1.2
  uuid: ^4.4.0
  package_info_plus: ^8.0.0
  device_info_plus: ^11.1.0
  connectivity_plus: ^6.0.3
  flutter_secure_storage: ^9.2.2
  permission_handler: ^11.3.1
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  flutter_tts: ^4.0.2
  google_speech: ^5.3.0
  flutter_svg: ^2.0.10+1
  flutter_math_fork: ^0.7.2
  flutter_quill: ^11.4.1
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1
  flutter_slidable: ^3.1.0
  flutter_local_notifications: ^17.2.1
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ai_model/Qwen2-VL-2B-Instruct-Q4_K_M.gguf
    - assets/icons/