name: neonote

description: A Flutter note-taking app with AI capabilities

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  path: ^1.8.3
  path_provider: ^2.1.1
  file_picker: ^10.2.0
  shared_preferences: ^2.2.2
  markdown: ^7.2.1
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.2
  ffi: ^2.1.0
  provider: ^6.1.1
  uuid: ^4.2.1
  package_info_plus: ^4.2.0
  device_info_plus: ^10.1.2
  connectivity_plus: ^5.0.2
  flutter_secure_storage: ^9.0.0
  permission_handler: ^11.0.1
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  intl: 0.19.0
  image_picker: ^1.0.4
  flutter_tts: ^3.8.3
  google_speech: ^5.3.0
  flutter_svg: ^2.0.7
  flutter_math_fork: ^0.7.2
  flutter_quill: ^11.4.1
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.1.0
  flutter_slidable: ^3.0.1
  flutter_local_notifications: ^16.3.2
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ai_model/Qwen2-VL-2B-Instruct-Q4_K_M.gguf
    - assets/icons/